/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.conexion;
import static Vista.formularioRegistro.txtApellido;
import static Vista.formularioRegistro.txtBarrio;
import static Vista.formularioRegistro.txtCI;
import static Vista.formularioRegistro.txtDir;
import static Vista.formularioRegistro.txtEC;
import static Vista.formularioRegistro.txtFI;
import static Vista.formularioRegistro.txtFechaN;
import static Vista.formularioRegistro.txtLD1;
import static Vista.formularioRegistro.txtNombre;
import static Vista.formularioRegistro.txtSex;
import static Vista.formularioRegistro.txtTel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ModificacionCRR extends javax.swing.JFrame {

    /**
     * Creates new form ModificacionCRR
     */
    public ModificacionCRR() {
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarDatos();
    }
    void MostrarDatos (){
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("CI");
        modelo.addColumn("Fecha Nacimiento");
        modelo.addColumn("Telefono");
        modelo.addColumn("Direccion");
        modelo.addColumn("Licencia de Conducir");
        modelo.addColumn("Fecha de Ingreso");
        modelo.addColumn("Barrio");
        modelo.addColumn("Estado Civil");
        modelo.addColumn("Sexo");
        tbMuestra.setModel(modelo);
        conexion con = new conexion();
        Connection cn = con.getConexion();
        String []datos = new String [12];
        try {
            Statement  st= cn.createStatement ();
            ResultSet rs= st.executeQuery("SELECT * FROM  personas");
            while (rs.next()){
                datos [0]=rs.getString(1);
                datos [1]=rs.getString(2);
                datos [2]=rs.getString(3);
                datos [3]=rs.getString(4);
                datos [4]=rs.getString(5);
                datos [5]=rs.getString(6);
                datos [6]=rs.getString(7);
                datos [7]=rs.getString(8);
                datos [8]=rs.getString(9);
                datos [9]=rs.getString(10);
                datos [10]=rs.getString(11);
                datos [11]=rs.getString(12);
                modelo.addRow(datos);
            }
            tbMuestra.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(ModificacionCRR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMuestra = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setText("Volver a opciones de Admin");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tbMuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbMuestra.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tbMuestra);

        btnImprimir.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Adm bck = new Adm();
        bck.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        formularioRegistro va = new formularioRegistro();
        va.setVisible(true);
        int fila = tbMuestra.getSelectedRow();
        if (fila>=1){
            txtNombre.setText(tbMuestra.getValueAt(fila, 1).toString());
            txtApellido.setText(tbMuestra.getValueAt(fila, 2).toString());
            txtCI.setText(tbMuestra.getValueAt(fila, 3).toString());
            txtFechaN.setText(tbMuestra.getValueAt(fila, 4).toString());
            txtTel.setText(tbMuestra.getValueAt(fila, 5).toString());
            txtDir.setText(tbMuestra.getValueAt(fila, 6).toString());
            txtLD1.setText(tbMuestra.getValueAt(fila, 7).toString());
            txtFI.setText(tbMuestra.getValueAt(fila, 8).toString());
            txtBarrio.setText(tbMuestra.getValueAt(fila, 9).toString());
            txtEC.setText(tbMuestra.getValueAt(fila, 10).toString());
            txtSex.setText(tbMuestra.getValueAt(fila, 11).toString());
        }
        else {
            JOptionPane.showMessageDialog(null,"No ha seleccionado la Fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        /*int fila1 = tbMuestra.getSelectedRow();
        System.out.println("FILA 1: "+fila1);
        String ci;
        ci=tbMuestra.getValueAt(fila1, 3).toString();
        conexion con = new conexion();
        Connection cn = con.getConexion();*/
        try {
             /*if (fila1>1){
            JOptionPane.showMessageDialog(null,"No ha seleccionado la Fila");
             }
             else{
            PreparedStatement psi = cn.prepareStatement("DELETE FROM personas WHERE CI_PERS='"+ci+"'");
            psi.executeUpdate();
            MostrarDatos();
             }*/
            int fila1 = tbMuestra.getSelectedRow();
            //System.out.println("FILA 1: "+fila1);
            String ci;
            ci=tbMuestra.getValueAt(fila1, 3).toString();  
            conexion con = new conexion();
            Connection cn = con.getConexion();
            PreparedStatement psi = cn.prepareStatement("DELETE FROM personas WHERE CI_PERS='"+ci+"'");
            psi.executeUpdate();
        } catch (Exception ex) {
            //Logger.getLogger(ModificacionCRR.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No ha seleccionado la Fila");
            //System.out.println("ex: "+ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacionCRR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacionCRR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacionCRR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacionCRR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificacionCRR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMuestra;
    // End of variables declaration//GEN-END:variables
}
